services:
  # Postgres
  postgres_db:
    image: postgres:16-alpine
    container_name: wallet-postgres
    environment:
      POSTGRES_DB: wallet_api_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rest-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d wallet_api_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # app
  app:
    image: maven:3.9-eclipse-temurin-17
    container_name: wallet-app
    ports:
      - "8085:8085"
    volumes:
      - ../:/app
    working_dir: /app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/wallet_api_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
    command: mvn spring-boot:run
    depends_on:
      postgres_db:
        condition: service_healthy
    networks:
      - rest-network

networks:
  rest-network:

volumes:
  postgres_data: